language: python

python:
  - "3.6"



install:
  - pip install -r requirements.txt
  - pip install coveralls codecov
  - pip install codeclimate-test-reporter

dist: trusty

services:
  - postgresql

  before_script:
  - psql -c "CREATE DATABASE test_db" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'admin';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres;" -U postgres

env:
  test_url = "dbname = 'test_db' user = 'postgres' host = 'localhost' port = '5432' password = 'admin'"
  FLASK_VERSION=1.0.2

script:
  - nosetests --with-coverage --cover-package=tests && coverage report

after_success:
  - coveralls
  - codeclimate-test-reporter