language: python

python:
  - "3.6"

env:
  db_url = "dbname = 'stackoverflow_db' user = 'postgres' host = 'localhost' port = '5432'  password = 'admin'"
  test_url = "dbname = 'test_db' user = 'postgres' host = 'localhost' port = '5432' password = 'admin'"
  FLASK_VERSION=1.0.2

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov
  - pip install codeclimate-test-reporter

services:
  - postgresql

addons:
  postgresql: "10.6"

before_script:
  - psql -c "CREATE DATABASE stackoverflow_db" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres;" -U postgres

script:
  - nosetests --with-coverage --cover-package=tests && coverage report

after_success:
  - coveralls
  - codeclimate-test-reporter